GET http://127.0.0.1:5000/hello

###

POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "username": "jdoe",
    "password": "password"
}

###

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "username": "jdoe",
    "password": "password"
}

###

GET http://127.0.0.1:5000/secret
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8

###

GET http://127.0.0.1:5000/tasks/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8

###

POST http://127.0.0.1:5000/tasks/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8
Content-Type: application/json

{
    "body": "This is a task"
}

###

PATCH http://127.0.0.1:5000/tasks/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8
Content-Type: application/json

{
    "body": "Updating the task"
}

###

DELETE http://127.0.0.1:5000/tasks/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8

###

GET http://127.0.0.1:5000/user/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8

###

PATCH http://127.0.0.1:5000/user/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8
Content-Type: application/json

{
    "name": "John Doe"
}

###

DELETE http://127.0.0.1:5000/user/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJwYXNzd29yZCI6InBia2RmMjpzaGEyNTY6MjYwMDAwJGFoQ3dTYllnT0hHN1lMODEkOGU3NzEwMzJjODA4ZmJmY2Q3MTA1OWRhZWNmNDE4Yjc1MjZkZGUyMTk4NDA3MDA2Y2IwMThjYTYwMGU0N2UzOCIsImV4cCI6MTYzNjcyOTIwOC45ODkxNDd9.AFY_-60uVMbY81Y95-x72ZRf8_-lRzu_ptWAeCBkum8
